#active profile
spring:
  profiles:
    active: dev

  # 404 以异常形式暴露，并关闭spring url的自动映射，
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/moonstar?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678

server:
  port: 50001
  tomcat:
      access-log-enabled: true
      access-log-pattern: common
      accesslog.directory: /tmp/logs/moonstar/access.log

  servlet:
    session:
      cookie:
        name: JSESSIONID_ALERT

mybatis:
  typeAliasesPackage: com.github.moonstar.entity
  mapperLocations: classpath:mapper/*.xml

